language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install -n
  - php app/console doctrine:schema:create -n --env test
  - php app/console doctrine:fixtures:load -n --env test

script: php bin/codecept run
