language: php
sudo: false

env:
  global:
    - SYMFONY_VERSION=""


matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: SYMFONY_VERSION="2.7.x"
    - php: 5.5
    - php: 5.6
      env: SYMFONY_VERSION="2.8.x"
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi

install:
  - composer install -n

before_script:
  - php app/console doctrine:schema:create -n --env test
  - php app/console doctrine:fixtures:load -n --env test

script:
  - php bin/codecept run -c src/AppBundle/
  
